title: Customer manager
description: Simple customer management application
version: 1.0
data:
  - description: Application Data
  - import
    - name: model
    - namespace: default
  - vars:
    - session-config:
      - authenticated-user: Session User
  - constants:
    - application-name: Customer Manager
operations:
  - description: Application Operations
  - import
    - name: transactions
    - namespace: default
  - import
    - name: scenarios
    - namespace: default
  